Models/NivelMaturidade.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelMaturidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NivelMaturidade()
        {
            this.AreaProcesso = new HashSet<AreaProcesso>();
        }
    
        public int IdNivelMaturidade { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaProcesso> AreaProcesso { get; set; }
    }
}

Controllers/AreaProcessoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AkaelApplication.Models;

namespace AkaelApplication.Controllers
{
    public class AreaProcessoController : Controller
    {
        private DatabaseAkaelEntities db = new DatabaseAkaelEntities();

        // GET: AreaProcesso
        public ActionResult Index()
        {
            var areaProcesso = db.AreaProcesso.Include(a => a.Categoria).Include(a => a.Modelo).Include(a => a.NivelMaturidade);
            return View(areaProcesso.ToList());
        }

        // GET: AreaProcesso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var item = (from ap in db.AreaProcesso
                        join mg in db.MetaGenerica on ap.IdAreaProcesso equals mg.IdMetaGenerica
                        join model in db.Modelo on ap.IdAreaProcesso equals model.IdModelo
                        from nc in db.NivelCapacidade
                        from c in db.Categoria
                        join me in db.MetaEspecifica on ap.IdAreaProcesso equals me.IdAreaProcesso
                        where ap.IdAreaProcesso == id.Value
                        select new AreaProcessoModelView()
                        {
                            SiglaMetaGenerica = mg.Sigla,
                            NomeMetaGenerica = mg.Nome,
                            DescricaoMetaGenerica = mg.Descricao,
                            Sigla = ap.Sigla,
                            Nome = ap.Nome,
                            Descricao = ap.Descricao,
                            SiglaModelo = model.Sigla,
                            NomeModelo = model.Nome,
                            DescricaoModelo = model.Descricao,
                            SiglaNivelCapacidade = nc.Sigla,
                            NomeNivelCapacidade = nc.Nome,
                            DescricaoNivelCapacidade = nc.Descricao,
                            NomeCategoria = c.Nome,
                            SiglaMetaEspecifica = me.Sigla,
                            NomeMetaEspecifica = me.Nome,
                            DescricaoMetaEspecifica = me.Descricao
                        }).FirstOrDefault();

            if (item == null)
            {
                return HttpNotFound();  // Or a return a view with message "item not found"
            }
            return View(item);
        }

        // GET: AreaProcesso/Create
        public ActionResult Create()
        {
            ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "Nome");
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla");
            ViewBag.IdNivelMaturidade = new SelectList(db.NivelMaturidade, "IdNivelMaturidade", "Sigla");
            return View();
        }

        // POST: AreaProcesso/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAreaProcesso,Sigla,Nome,Descricao,IdNivelMaturidade,IdCategoria,IdModelo")] AreaProcesso areaProcesso)
        {
            if (ModelState.IsValid)
            {
                db.AreaProcesso.Add(areaProcesso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "Nome", areaProcesso.IdCategoria);
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", areaProcesso.IdModelo);
            ViewBag.IdNivelMaturidade = new SelectList(db.NivelMaturidade, "IdNivelMaturidade", "Sigla", areaProcesso.IdNivelMaturidade);
            return View(areaProcesso);
        }

        // GET: AreaProcesso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AreaProcesso areaProcesso = db.AreaProcesso.Find(id);
            if (areaProcesso == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "Nome", areaProcesso.IdCategoria);
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", areaProcesso.IdModelo);
            ViewBag.IdNivelMaturidade = new SelectList(db.NivelMaturidade, "IdNivelMaturidade", "Sigla", areaProcesso.IdNivelMaturidade);
            return View(areaProcesso);
        }

        // POST: AreaProcesso/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAreaProcesso,Sigla,Nome,Descricao,IdNivelMaturidade,IdCategoria,IdModelo")] AreaProcesso areaProcesso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(areaProcesso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "Nome", areaProcesso.IdCategoria);
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", areaProcesso.IdModelo);
            ViewBag.IdNivelMaturidade = new SelectList(db.NivelMaturidade, "IdNivelMaturidade", "Sigla", areaProcesso.IdNivelMaturidade);
            return View(areaProcesso);
        }

        // GET: AreaProcesso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AreaProcesso areaProcesso = db.AreaProcesso.Find(id);
            if (areaProcesso == null)
            {
                return HttpNotFound();
            }
            return View(areaProcesso);
        }

        // POST: AreaProcesso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AreaProcesso areaProcesso = db.AreaProcesso.Find(id);
            db.AreaProcesso.Remove(areaProcesso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/NivelMaturidadeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AkaelApplication.Models;

namespace AkaelApplication.Controllers
{
    public class NivelMaturidadeController : Controller
    {
        private DatabaseAkaelEntities db = new DatabaseAkaelEntities();

        // GET: NivelMaturidade
        public ActionResult Index()
        {
            return View(db.NivelMaturidade.ToList());
        }

        // GET: NivelMaturidade/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NivelMaturidade nivelMaturidade = db.NivelMaturidade.Find(id);
            if (nivelMaturidade == null)
            {
                return HttpNotFound();
            }
            return View(nivelMaturidade);
        }

        // GET: NivelMaturidade/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NivelMaturidade/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdNivelMaturidade,Sigla,Nome,Descricao")] NivelMaturidade nivelMaturidade)
        {
            if (ModelState.IsValid)
            {
                db.NivelMaturidade.Add(nivelMaturidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nivelMaturidade);
        }

        // GET: NivelMaturidade/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NivelMaturidade nivelMaturidade = db.NivelMaturidade.Find(id);
            if (nivelMaturidade == null)
            {
                return HttpNotFound();
            }
            return View(nivelMaturidade);
        }

        // POST: NivelMaturidade/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdNivelMaturidade,Sigla,Nome,Descricao")] NivelMaturidade nivelMaturidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nivelMaturidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nivelMaturidade);
        }

        // GET: NivelMaturidade/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NivelMaturidade nivelMaturidade = db.NivelMaturidade.Find(id);
            if (nivelMaturidade == null)
            {
                return HttpNotFound();
            }
            return View(nivelMaturidade);
        }

        // POST: NivelMaturidade/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NivelMaturidade nivelMaturidade = db.NivelMaturidade.Find(id);
            db.NivelMaturidade.Remove(nivelMaturidade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/NivelMaturidade/Create.cshtml
@model AkaelApplication.Models.NivelMaturidade

@{
    ViewBag.Title = "Create";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Níveis de Maturidade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
    @Html.ActionLink("Avançar", "Create", "AreaProcesso")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NivelMaturidade/Delete.cshtml
@model AkaelApplication.Models.NivelMaturidade

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja deletar?</h3>
<div>
    <h4>Níveis de Maturidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>

Views/NivelMaturidade/Details.cshtml
@model AkaelApplication.Models.NivelMaturidade

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Níveis de Maturidade</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdNivelMaturidade }) |
    @Html.ActionLink("Voltar à lista", "Index")
</p>

Views/NivelMaturidade/Edit.cshtml
@model AkaelApplication.Models.NivelMaturidade

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Níveis de Maturidade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdNivelMaturidade)

        <div class="form-group">
            @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/NivelMaturidade/Index.cshtml
@model IEnumerable<AkaelApplication.Models.NivelMaturidade>

@{
    ViewBag.Title = "Index";
}

<h2>Níveis de Maturidade</h2>

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sigla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sigla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IdNivelMaturidade }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.IdNivelMaturidade }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.IdNivelMaturidade })
        </td>
    </tr>
}

</table>