Models/MetaGenerica.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkaelApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaGenerica
    {
        public int IdMetaGenerica { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int IdNivelCapacidade { get; set; }
        public int IdModelo { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual NivelCapacidade NivelCapacidade { get; set; }
    }
}

Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AkaelApplication.Models;

namespace AkaelApplication.Controllers
{
    public class CategoriaController : Controller
    {
        private DatabaseAkaelEntities db = new DatabaseAkaelEntities();

        // GET: Categoria
        public ActionResult Index()
        {
            return View(db.Categoria.ToList());
        }

        // GET: Categoria/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCategoria,Nome")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Categoria.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: Categoria/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categoria/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCategoria,Nome")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categoria/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categoria.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categoria/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = db.Categoria.Find(id);
            db.Categoria.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/MetaGenericaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AkaelApplication.Models;

namespace AkaelApplication.Controllers
{
    public class MetaGenericaController : Controller
    {
        private DatabaseAkaelEntities db = new DatabaseAkaelEntities();

        // GET: MetaGenerica
        public ActionResult Index()
        {
            var metaGenerica = db.MetaGenerica.Include(m => m.Modelo).Include(m => m.NivelCapacidade);
            return View(metaGenerica.ToList());
        }

        // GET: MetaGenerica/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MetaGenerica metaGenerica = db.MetaGenerica.Find(id);
            if (metaGenerica == null)
            {
                return HttpNotFound();
            }
            return View(metaGenerica);
        }

        // GET: MetaGenerica/Create
        public ActionResult Create()
        {
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla");
            ViewBag.IdNivelCapacidade = new SelectList(db.NivelCapacidade, "IdNivelCapacidade", "Sigla");
            return View();
        }

        // POST: MetaGenerica/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMetaGenerica,Sigla,Nome,Descricao,IdNivelCapacidade,IdModelo")] MetaGenerica metaGenerica)
        {
            if (ModelState.IsValid)
            {
                db.MetaGenerica.Add(metaGenerica);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", metaGenerica.IdModelo);
            ViewBag.IdNivelCapacidade = new SelectList(db.NivelCapacidade, "IdNivelCapacidade", "Sigla", metaGenerica.IdNivelCapacidade);
            return View(metaGenerica);
        }

        // GET: MetaGenerica/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MetaGenerica metaGenerica = db.MetaGenerica.Find(id);
            if (metaGenerica == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", metaGenerica.IdModelo);
            ViewBag.IdNivelCapacidade = new SelectList(db.NivelCapacidade, "IdNivelCapacidade", "Sigla", metaGenerica.IdNivelCapacidade);
            return View(metaGenerica);
        }

        // POST: MetaGenerica/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdMetaGenerica,Sigla,Nome,Descricao,IdNivelCapacidade,IdModelo")] MetaGenerica metaGenerica)
        {
            if (ModelState.IsValid)
            {
                db.Entry(metaGenerica).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdModelo = new SelectList(db.Modelo, "IdModelo", "Sigla", metaGenerica.IdModelo);
            ViewBag.IdNivelCapacidade = new SelectList(db.NivelCapacidade, "IdNivelCapacidade", "Sigla", metaGenerica.IdNivelCapacidade);
            return View(metaGenerica);
        }

        // GET: MetaGenerica/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MetaGenerica metaGenerica = db.MetaGenerica.Find(id);
            if (metaGenerica == null)
            {
                return HttpNotFound();
            }
            return View(metaGenerica);
        }

        // POST: MetaGenerica/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MetaGenerica metaGenerica = db.MetaGenerica.Find(id);
            db.MetaGenerica.Remove(metaGenerica);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/MetaGenerica/Create.cshtml
@model AkaelApplication.Models.MetaGenerica

@{
    ViewBag.Title = "Create";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Metas Genérica</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNivelCapacidade, "IdNivelCapacidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdNivelCapacidade", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdNivelCapacidade, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdModelo, "IdModelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdModelo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdModelo, "", new { @class = "text-danger", required = "required" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
    @Html.ActionLink("Avançar", "Create", "Categoria")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MetaGenerica/Delete.cshtml
@model AkaelApplication.Models.MetaGenerica

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja deletar?</h3>
<div>
    <h4>Metas Genérica</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NivelCapacidade.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NivelCapacidade.Sigla)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar à lista", "Index")
        </div>
    }
</div>

Views/MetaGenerica/Details.cshtml
@model AkaelApplication.Models.MetaGenerica

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Metas Genéricas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo.Sigla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NivelCapacidade.Sigla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NivelCapacidade.Sigla)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdMetaGenerica }) |
    @Html.ActionLink("Voltar à Lista", "Index")
</p>

Views/MetaGenerica/Edit.cshtml
@model AkaelApplication.Models.MetaGenerica

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Metas Genéricas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdMetaGenerica)

        <div class="form-group">
            @Html.LabelFor(model => model.Sigla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sigla, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sigla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdNivelCapacidade, "IdNivelCapacidade", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdNivelCapacidade", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdNivelCapacidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdModelo, "IdModelo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdModelo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdModelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/MetaGenerica/Index.cshtml
@model IEnumerable<AkaelApplication.Models.MetaGenerica>

@{
    ViewBag.Title = "Index";
}

<h2>Metas Genéricas</h2>

<p>
    @Html.ActionLink("Criar Nova", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sigla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo.Sigla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NivelCapacidade.Sigla)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Sigla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo.Sigla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NivelCapacidade.Sigla)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IdMetaGenerica }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.IdMetaGenerica }) |
            @Html.ActionLink("Deletar", "Delete", new { id=item.IdMetaGenerica })
        </td>
    </tr>
}

</table>